apiVersion: apps/v1

kind: Deployment

metadata:
  name: simple-app-deployment
  namespace: desarrollo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app-container
        image: dirac22/simple-app:1.1.0
        imagePullPolicy: IfNotPresent